<?php

namespace Database\Seeders;

use App\Models\FlashCard;
use Illuminate\Database\Seeder;

class FlashCardSeeder extends Seeder
{
    /**
     * Seed the application's database with B1/B2 German vocabulary.
     */
    public function run(): void
    {
        $cards = [
            // Food & Cooking
            ['german' => 'die Zutat', 'english' => 'ingredient', 'example_sentence' => 'Wir brauchen noch eine Zutat für den Kuchen.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'das Rezept', 'english' => 'recipe', 'example_sentence' => 'Hast du ein gutes Rezept für Kartoffelsuppe?', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'die Mahlzeit', 'english' => 'meal', 'example_sentence' => 'Die Mahlzeit war wirklich lecker.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'die Beilage', 'english' => 'side dish', 'example_sentence' => 'Als Beilage nehme ich Reis.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'die Pfanne', 'english' => 'pan', 'example_sentence' => 'Erhitze das Öl in der Pfanne.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'der Topf', 'english' => 'pot', 'example_sentence' => 'Das Wasser kocht schon im Topf.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'braten', 'english' => 'to fry / to roast', 'example_sentence' => 'Ich brate das Fleisch bei mittlerer Hitze.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'kochen', 'english' => 'to cook / to boil', 'example_sentence' => 'Heute Abend koche ich Pasta.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'schmecken', 'english' => 'to taste', 'example_sentence' => 'Die Suppe schmeckt nach Tomaten.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'die Vorspeise', 'english' => 'appetizer / starter', 'example_sentence' => 'Als Vorspeise bestelle ich den Salat.', 'category' => 'Food & Cooking', 'level' => 'B2'],
            ['german' => 'die Nachspeise', 'english' => 'dessert', 'example_sentence' => 'Möchten Sie noch eine Nachspeise?', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'würzen', 'english' => 'to season', 'example_sentence' => 'Du solltest die Soße noch etwas würzen.', 'category' => 'Food & Cooking', 'level' => 'B2'],
            ['german' => 'das Gewürz', 'english' => 'spice', 'example_sentence' => 'Welches Gewürz passt am besten zu Fisch?', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'rühren', 'english' => 'to stir', 'example_sentence' => 'Bitte rühre die Soße regelmäßig um.', 'category' => 'Food & Cooking', 'level' => 'B2'],
            ['german' => 'backen', 'english' => 'to bake', 'example_sentence' => 'Am Wochenende backe ich einen Apfelkuchen.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'die Scheibe', 'english' => 'slice', 'example_sentence' => 'Möchtest du eine Scheibe Brot?', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'die Portion', 'english' => 'portion / serving', 'example_sentence' => 'Die Portion war viel zu groß für mich.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'schälen', 'english' => 'to peel', 'example_sentence' => 'Kannst du bitte die Kartoffeln schälen?', 'category' => 'Food & Cooking', 'level' => 'B2'],
            ['german' => 'die Soße', 'english' => 'sauce / gravy', 'example_sentence' => 'Die Soße ist selbst gemacht.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'der Teig', 'english' => 'dough', 'example_sentence' => 'Der Teig muss eine Stunde ruhen.', 'category' => 'Food & Cooking', 'level' => 'B2'],
            ['german' => 'die Schüssel', 'english' => 'bowl', 'example_sentence' => 'Gib das Mehl in eine große Schüssel.', 'category' => 'Food & Cooking', 'level' => 'B1'],
            ['german' => 'das Besteck', 'english' => 'cutlery', 'example_sentence' => 'Das Besteck liegt in der Schublade.', 'category' => 'Food & Cooking', 'level' => 'B1'],

            // Health & Body
            ['german' => 'die Erkältung', 'english' => 'cold (illness)', 'example_sentence' => 'Ich habe eine starke Erkältung.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'das Fieber', 'english' => 'fever', 'example_sentence' => 'Das Kind hat seit gestern Fieber.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'der Husten', 'english' => 'cough', 'example_sentence' => 'Mein Husten wird einfach nicht besser.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'der Schnupfen', 'english' => 'runny nose / cold', 'example_sentence' => 'Im Winter habe ich oft Schnupfen.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'die Behandlung', 'english' => 'treatment', 'example_sentence' => 'Die Behandlung dauert etwa sechs Wochen.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'die Untersuchung', 'english' => 'examination', 'example_sentence' => 'Die Untersuchung beim Arzt war gründlich.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'das Rezept', 'english' => 'prescription', 'example_sentence' => 'Der Arzt hat mir ein Rezept ausgestellt.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'die Apotheke', 'english' => 'pharmacy', 'example_sentence' => 'Ich hole die Medikamente in der Apotheke.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'sich erholen', 'english' => 'to recover', 'example_sentence' => 'Nach der Operation muss er sich erholen.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Sprechstunde', 'english' => 'consultation hours', 'example_sentence' => 'Die Sprechstunde ist von 8 bis 12 Uhr.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Überweisung', 'english' => 'referral', 'example_sentence' => 'Ich brauche eine Überweisung zum Facharzt.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Nebenwirkung', 'english' => 'side effect', 'example_sentence' => 'Dieses Medikament hat kaum Nebenwirkungen.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'das Immunsystem', 'english' => 'immune system', 'example_sentence' => 'Sport stärkt das Immunsystem.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Entzündung', 'english' => 'inflammation', 'example_sentence' => 'Die Entzündung im Knie ist noch nicht weg.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Salbe', 'english' => 'ointment', 'example_sentence' => 'Tragen Sie die Salbe zweimal täglich auf.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'der Verband', 'english' => 'bandage', 'example_sentence' => 'Der Verband muss jeden Tag gewechselt werden.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'die Spritze', 'english' => 'injection / syringe', 'example_sentence' => 'Die Spritze hat gar nicht wehgetan.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'der Blutdruck', 'english' => 'blood pressure', 'example_sentence' => 'Mein Blutdruck ist heute zu hoch.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Allergie', 'english' => 'allergy', 'example_sentence' => 'Sie hat eine Allergie gegen Nüsse.', 'category' => 'Health & Body', 'level' => 'B1'],
            ['german' => 'nüchtern', 'english' => 'sober / on an empty stomach', 'example_sentence' => 'Zur Blutabnahme müssen Sie nüchtern kommen.', 'category' => 'Health & Body', 'level' => 'B2'],
            ['german' => 'die Krankenkasse', 'english' => 'health insurance', 'example_sentence' => 'Die Krankenkasse übernimmt die Kosten.', 'category' => 'Health & Body', 'level' => 'B1'],

            // Work & Career
            ['german' => 'die Bewerbung', 'english' => 'application (job)', 'example_sentence' => 'Ich habe meine Bewerbung gestern abgeschickt.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'der Lebenslauf', 'english' => 'CV / resume', 'example_sentence' => 'Dein Lebenslauf sollte aktuell sein.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'das Vorstellungsgespräch', 'english' => 'job interview', 'example_sentence' => 'Mein Vorstellungsgespräch ist am Montag.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Stelle', 'english' => 'position / job', 'example_sentence' => 'Er hat eine neue Stelle als Ingenieur gefunden.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'der Arbeitgeber', 'english' => 'employer', 'example_sentence' => 'Mein Arbeitgeber bietet flexible Arbeitszeiten an.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'der Arbeitnehmer', 'english' => 'employee', 'example_sentence' => 'Der Arbeitnehmer hat Recht auf Urlaub.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Kündigung', 'english' => 'resignation / dismissal', 'example_sentence' => 'Er hat seine Kündigung eingereicht.', 'category' => 'Work & Career', 'level' => 'B2'],
            ['german' => 'die Beförderung', 'english' => 'promotion', 'example_sentence' => 'Sie hat eine Beförderung zur Teamleiterin bekommen.', 'category' => 'Work & Career', 'level' => 'B2'],
            ['german' => 'das Gehalt', 'english' => 'salary', 'example_sentence' => 'Das Gehalt wird am Ende des Monats gezahlt.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Überstunde', 'english' => 'overtime', 'example_sentence' => 'Diese Woche habe ich viele Überstunden gemacht.', 'category' => 'Work & Career', 'level' => 'B2'],
            ['german' => 'die Weiterbildung', 'english' => 'further education / training', 'example_sentence' => 'Die Firma bezahlt meine Weiterbildung.', 'category' => 'Work & Career', 'level' => 'B2'],
            ['german' => 'die Abteilung', 'english' => 'department', 'example_sentence' => 'In welcher Abteilung arbeitest du?', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Frist', 'english' => 'deadline', 'example_sentence' => 'Die Frist für die Abgabe ist nächsten Freitag.', 'category' => 'Work & Career', 'level' => 'B2'],
            ['german' => 'der Vertrag', 'english' => 'contract', 'example_sentence' => 'Ich habe den Vertrag unterschrieben.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Teilzeit', 'english' => 'part-time', 'example_sentence' => 'Sie arbeitet in Teilzeit, nur drei Tage pro Woche.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Vollzeit', 'english' => 'full-time', 'example_sentence' => 'Er sucht eine Vollzeit-Stelle.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'der Kollege', 'english' => 'colleague', 'example_sentence' => 'Mein Kollege hilft mir bei dem Projekt.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Besprechung', 'english' => 'meeting', 'example_sentence' => 'Die Besprechung beginnt um 10 Uhr.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'die Geschäftsreise', 'english' => 'business trip', 'example_sentence' => 'Nächste Woche bin ich auf Geschäftsreise.', 'category' => 'Work & Career', 'level' => 'B2'],
            ['german' => 'der Feierabend', 'english' => 'end of the workday', 'example_sentence' => 'Nach Feierabend gehe ich ins Fitnessstudio.', 'category' => 'Work & Career', 'level' => 'B1'],
            ['german' => 'der Urlaub', 'english' => 'vacation / holiday', 'example_sentence' => 'Im August fahren wir in den Urlaub.', 'category' => 'Work & Career', 'level' => 'B1'],

            // Housing & Home
            ['german' => 'die Wohnung', 'english' => 'apartment', 'example_sentence' => 'Die Wohnung hat drei Zimmer und einen Balkon.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'die Miete', 'english' => 'rent', 'example_sentence' => 'Die Miete beträgt 800 Euro pro Monat.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Vermieter', 'english' => 'landlord', 'example_sentence' => 'Der Vermieter hat die Heizung repariert.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Mieter', 'english' => 'tenant', 'example_sentence' => 'Der neue Mieter zieht nächste Woche ein.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'die Nebenkosten', 'english' => 'utility costs', 'example_sentence' => 'Die Nebenkosten sind dieses Jahr gestiegen.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'die Kaution', 'english' => 'deposit (rental)', 'example_sentence' => 'Die Kaution beträgt zwei Monatsmieten.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'der Mietvertrag', 'english' => 'lease agreement', 'example_sentence' => 'Lies den Mietvertrag sorgfältig durch.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'umziehen', 'english' => 'to move (house)', 'example_sentence' => 'Wir ziehen nächsten Monat in eine größere Wohnung um.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'einrichten', 'english' => 'to furnish / set up', 'example_sentence' => 'Wir müssen das Kinderzimmer noch einrichten.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'renovieren', 'english' => 'to renovate', 'example_sentence' => 'Wir wollen das Bad renovieren.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'das Stockwerk', 'english' => 'floor / storey', 'example_sentence' => 'Mein Büro ist im dritten Stockwerk.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Aufzug', 'english' => 'elevator', 'example_sentence' => 'Der Aufzug ist leider außer Betrieb.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'die Heizung', 'english' => 'heating', 'example_sentence' => 'Im Winter läuft die Heizung den ganzen Tag.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Strom', 'english' => 'electricity', 'example_sentence' => 'Der Strom ist heute ausgefallen.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Keller', 'english' => 'basement / cellar', 'example_sentence' => 'Die alten Möbel stehen im Keller.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Dachboden', 'english' => 'attic', 'example_sentence' => 'Auf dem Dachboden gibt es noch viel Platz.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'die Treppe', 'english' => 'stairs', 'example_sentence' => 'Sei vorsichtig auf der Treppe!', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Balkon', 'english' => 'balcony', 'example_sentence' => 'Im Sommer frühstücken wir auf dem Balkon.', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'die Garderobe', 'english' => 'wardrobe / cloakroom', 'example_sentence' => 'Häng deinen Mantel bitte an die Garderobe.', 'category' => 'Housing & Home', 'level' => 'B2'],
            ['german' => 'die Steckdose', 'english' => 'power outlet', 'example_sentence' => 'Wo ist hier die nächste Steckdose?', 'category' => 'Housing & Home', 'level' => 'B1'],
            ['german' => 'der Wasserhahn', 'english' => 'faucet / tap', 'example_sentence' => 'Der Wasserhahn in der Küche tropft.', 'category' => 'Housing & Home', 'level' => 'B2'],

            // Travel & Transport
            ['german' => 'die Fahrkarte', 'english' => 'ticket (transport)', 'example_sentence' => 'Ich habe meine Fahrkarte online gekauft.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'der Fahrplan', 'english' => 'timetable / schedule', 'example_sentence' => 'Schau mal im Fahrplan nach dem nächsten Zug.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Verspätung', 'english' => 'delay', 'example_sentence' => 'Der Zug hat zwanzig Minuten Verspätung.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'umsteigen', 'english' => 'to transfer / change', 'example_sentence' => 'In München müssen wir umsteigen.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Haltestelle', 'english' => 'stop (bus/tram)', 'example_sentence' => 'Die nächste Haltestelle ist am Marktplatz.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'der Stau', 'english' => 'traffic jam', 'example_sentence' => 'Wegen des Staus bin ich zu spät gekommen.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Unterkunft', 'english' => 'accommodation', 'example_sentence' => 'Wir haben eine günstige Unterkunft gefunden.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Sehenswürdigkeit', 'english' => 'sight / attraction', 'example_sentence' => 'Das Schloss ist die bekannteste Sehenswürdigkeit der Stadt.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Abfahrt', 'english' => 'departure', 'example_sentence' => 'Die Abfahrt ist um 8:30 Uhr.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Ankunft', 'english' => 'arrival', 'example_sentence' => 'Die Ankunft in Wien ist gegen Mittag.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'das Gleis', 'english' => 'platform / track', 'example_sentence' => 'Der Zug fährt von Gleis 5 ab.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Ermäßigung', 'english' => 'discount / reduction', 'example_sentence' => 'Studenten bekommen eine Ermäßigung.', 'category' => 'Travel & Transport', 'level' => 'B2'],
            ['german' => 'die Durchsage', 'english' => 'announcement', 'example_sentence' => 'Hast du die Durchsage am Bahnhof gehört?', 'category' => 'Travel & Transport', 'level' => 'B2'],
            ['german' => 'die Reiseversicherung', 'english' => 'travel insurance', 'example_sentence' => 'Vergiss nicht, eine Reiseversicherung abzuschließen.', 'category' => 'Travel & Transport', 'level' => 'B2'],
            ['german' => 'die Grenze', 'english' => 'border', 'example_sentence' => 'An der Grenze wurde mein Pass kontrolliert.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'der Reisepass', 'english' => 'passport', 'example_sentence' => 'Mein Reisepass ist noch drei Jahre gültig.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'das Gepäck', 'english' => 'luggage', 'example_sentence' => 'Mein Gepäck ist noch nicht angekommen.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Fähre', 'english' => 'ferry', 'example_sentence' => 'Die Fähre fährt zweimal am Tag zur Insel.', 'category' => 'Travel & Transport', 'level' => 'B2'],
            ['german' => 'der Flughafen', 'english' => 'airport', 'example_sentence' => 'Wir müssen zwei Stunden vor dem Flug am Flughafen sein.', 'category' => 'Travel & Transport', 'level' => 'B1'],
            ['german' => 'die Kreuzung', 'english' => 'intersection / crossroads', 'example_sentence' => 'An der nächsten Kreuzung biegst du links ab.', 'category' => 'Travel & Transport', 'level' => 'B1'],

            // Education & Learning
            ['german' => 'die Prüfung', 'english' => 'exam', 'example_sentence' => 'Die Prüfung war schwieriger als erwartet.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'bestehen', 'english' => 'to pass (an exam)', 'example_sentence' => 'Sie hat die Prüfung mit einer guten Note bestanden.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'durchfallen', 'english' => 'to fail (an exam)', 'example_sentence' => 'Leider ist er durch die Prüfung durchgefallen.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'die Kenntnisse', 'english' => 'knowledge / skills', 'example_sentence' => 'Gute Englischkenntnisse sind für den Job erforderlich.', 'category' => 'Education & Learning', 'level' => 'B2'],
            ['german' => 'die Ausbildung', 'english' => 'vocational training', 'example_sentence' => 'Er macht eine Ausbildung als Elektriker.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'das Studium', 'english' => 'university studies', 'example_sentence' => 'Nach dem Studium möchte ich im Ausland arbeiten.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'der Abschluss', 'english' => 'degree / graduation', 'example_sentence' => 'Welchen Abschluss hast du gemacht?', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'die Vorlesung', 'english' => 'lecture', 'example_sentence' => 'Die Vorlesung beginnt um 9 Uhr.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'das Stipendium', 'english' => 'scholarship', 'example_sentence' => 'Sie hat ein Stipendium für ihr Studium bekommen.', 'category' => 'Education & Learning', 'level' => 'B2'],
            ['german' => 'die Nachhilfe', 'english' => 'tutoring', 'example_sentence' => 'Er gibt Nachhilfe in Mathematik.', 'category' => 'Education & Learning', 'level' => 'B2'],
            ['german' => 'sich anmelden', 'english' => 'to register / enroll', 'example_sentence' => 'Du musst dich für den Kurs online anmelden.', 'category' => 'Education & Learning', 'level' => 'B1'],
            ['german' => 'der Lehrplan', 'english' => 'curriculum', 'example_sentence' => 'Der Lehrplan wurde dieses Jahr geändert.', 'category' => 'Education & Learning', 'level' => 'B2'],

            // Shopping & Money
            ['german' => 'die Quittung', 'english' => 'receipt', 'example_sentence' => 'Kann ich bitte eine Quittung bekommen?', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'das Angebot', 'english' => 'offer / special deal', 'example_sentence' => 'Im Supermarkt gibt es diese Woche gute Angebote.', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'umtauschen', 'english' => 'to exchange / return', 'example_sentence' => 'Kann ich die Hose umtauschen?', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'die Rechnung', 'english' => 'bill / invoice', 'example_sentence' => 'Könnte ich bitte die Rechnung bekommen?', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'das Konto', 'english' => 'account (bank)', 'example_sentence' => 'Ich möchte ein neues Konto eröffnen.', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'überweisen', 'english' => 'to transfer (money)', 'example_sentence' => 'Ich überweise das Geld morgen.', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'die Schulden', 'english' => 'debts', 'example_sentence' => 'Er versucht, seine Schulden abzubezahlen.', 'category' => 'Shopping & Money', 'level' => 'B2'],
            ['german' => 'sparen', 'english' => 'to save (money)', 'example_sentence' => 'Wir sparen für eine Reise nach Japan.', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'ausgeben', 'english' => 'to spend', 'example_sentence' => 'Sie gibt zu viel Geld für Kleidung aus.', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'die Versicherung', 'english' => 'insurance', 'example_sentence' => 'Die Versicherung deckt den Schaden ab.', 'category' => 'Shopping & Money', 'level' => 'B2'],
            ['german' => 'der Rabatt', 'english' => 'discount', 'example_sentence' => 'Auf alle Jacken gibt es 20 Prozent Rabatt.', 'category' => 'Shopping & Money', 'level' => 'B1'],
            ['german' => 'die Ratenzahlung', 'english' => 'installment payment', 'example_sentence' => 'Das Auto kann man auch per Ratenzahlung kaufen.', 'category' => 'Shopping & Money', 'level' => 'B2'],

            // Emotions & Personality
            ['german' => 'begeistert', 'english' => 'enthusiastic / excited', 'example_sentence' => 'Die Kinder waren vom Ausflug begeistert.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'enttäuscht', 'english' => 'disappointed', 'example_sentence' => 'Ich bin von dem Film enttäuscht.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'erstaunt', 'english' => 'astonished', 'example_sentence' => 'Ich war erstaunt über seine Reaktion.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'eifersüchtig', 'english' => 'jealous', 'example_sentence' => 'Er ist eifersüchtig auf ihren Erfolg.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'selbstbewusst', 'english' => 'confident', 'example_sentence' => 'Sie tritt immer sehr selbstbewusst auf.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'zuverlässig', 'english' => 'reliable', 'example_sentence' => 'Er ist ein sehr zuverlässiger Mitarbeiter.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'neugierig', 'english' => 'curious', 'example_sentence' => 'Das Kind ist sehr neugierig und stellt viele Fragen.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'dankbar', 'english' => 'grateful', 'example_sentence' => 'Ich bin dir sehr dankbar für deine Hilfe.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'ängstlich', 'english' => 'anxious / fearful', 'example_sentence' => 'Der Hund ist bei Gewitter sehr ängstlich.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'großzügig', 'english' => 'generous', 'example_sentence' => 'Sie ist immer sehr großzügig mit Geschenken.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'hartnäckig', 'english' => 'persistent / stubborn', 'example_sentence' => 'Er ist hartnäckig und gibt nie auf.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'empfindlich', 'english' => 'sensitive', 'example_sentence' => 'Sie reagiert sehr empfindlich auf Kritik.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'verzweifelt', 'english' => 'desperate', 'example_sentence' => 'Er war verzweifelt, weil er keine Lösung fand.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'stolz', 'english' => 'proud', 'example_sentence' => 'Die Eltern sind stolz auf ihre Tochter.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'schüchtern', 'english' => 'shy', 'example_sentence' => 'Als Kind war ich sehr schüchtern.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'geduldig', 'english' => 'patient', 'example_sentence' => 'Ein guter Lehrer muss geduldig sein.', 'category' => 'Emotions & Personality', 'level' => 'B1'],
            ['german' => 'ehrgeizig', 'english' => 'ambitious', 'example_sentence' => 'Sie ist sehr ehrgeizig und will Ärztin werden.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'gelassen', 'english' => 'calm / composed', 'example_sentence' => 'Er bleibt auch in stressigen Situationen gelassen.', 'category' => 'Emotions & Personality', 'level' => 'B2'],
            ['german' => 'neidisch', 'english' => 'envious', 'example_sentence' => 'Sei nicht neidisch auf andere.', 'category' => 'Emotions & Personality', 'level' => 'B2'],

            // Environment & Nature
            ['german' => 'die Umwelt', 'english' => 'environment', 'example_sentence' => 'Wir müssen die Umwelt besser schützen.', 'category' => 'Environment & Nature', 'level' => 'B1'],
            ['german' => 'der Klimawandel', 'english' => 'climate change', 'example_sentence' => 'Der Klimawandel betrifft die ganze Welt.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'die Verschmutzung', 'english' => 'pollution', 'example_sentence' => 'Die Verschmutzung der Meere ist ein großes Problem.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'recyceln', 'english' => 'to recycle', 'example_sentence' => 'In Deutschland wird viel recycelt.', 'category' => 'Environment & Nature', 'level' => 'B1'],
            ['german' => 'die Mülltrennung', 'english' => 'waste separation', 'example_sentence' => 'Mülltrennung ist in Österreich Pflicht.', 'category' => 'Environment & Nature', 'level' => 'B1'],
            ['german' => 'erneuerbar', 'english' => 'renewable', 'example_sentence' => 'Erneuerbare Energien werden immer wichtiger.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'die Nachhaltigkeit', 'english' => 'sustainability', 'example_sentence' => 'Nachhaltigkeit spielt in der Wirtschaft eine große Rolle.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'der Naturschutz', 'english' => 'nature conservation', 'example_sentence' => 'Dieses Gebiet steht unter Naturschutz.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'das Gewitter', 'english' => 'thunderstorm', 'example_sentence' => 'Heute Nachmittag gibt es ein starkes Gewitter.', 'category' => 'Environment & Nature', 'level' => 'B1'],
            ['german' => 'die Überschwemmung', 'english' => 'flood', 'example_sentence' => 'Nach dem Regen gab es eine Überschwemmung.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'die Dürre', 'english' => 'drought', 'example_sentence' => 'Die Dürre hat die Ernte zerstört.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'die Quelle', 'english' => 'source / spring', 'example_sentence' => 'Das Wasser kommt direkt aus der Quelle.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'der Abfall', 'english' => 'waste / garbage', 'example_sentence' => 'Bitte wirf den Abfall in die richtige Tonne.', 'category' => 'Environment & Nature', 'level' => 'B1'],
            ['german' => 'der Lebensraum', 'english' => 'habitat', 'example_sentence' => 'Viele Tiere verlieren ihren natürlichen Lebensraum.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'aussterben', 'english' => 'to go extinct', 'example_sentence' => 'Viele Tierarten drohen auszusterben.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'die Ernte', 'english' => 'harvest', 'example_sentence' => 'Die Ernte war dieses Jahr sehr gut.', 'category' => 'Environment & Nature', 'level' => 'B2'],
            ['german' => 'der Schatten', 'english' => 'shadow / shade', 'example_sentence' => 'Lass uns im Schatten sitzen, es ist zu heiß.', 'category' => 'Environment & Nature', 'level' => 'B1'],

            // Media & Technology
            ['german' => 'die Nachricht', 'english' => 'message / news', 'example_sentence' => 'Hast du meine Nachricht gelesen?', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'die Sendung', 'english' => 'broadcast / show', 'example_sentence' => 'Diese Sendung kommt jeden Freitag.', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'der Beitrag', 'english' => 'contribution / post', 'example_sentence' => 'Sein Beitrag hat viele Kommentare bekommen.', 'category' => 'Media & Technology', 'level' => 'B2'],
            ['german' => 'herunterladen', 'english' => 'to download', 'example_sentence' => 'Du kannst die App kostenlos herunterladen.', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'die Anwendung', 'english' => 'application (software)', 'example_sentence' => 'Diese Anwendung braucht viel Speicherplatz.', 'category' => 'Media & Technology', 'level' => 'B2'],
            ['german' => 'das Passwort', 'english' => 'password', 'example_sentence' => 'Ich habe mein Passwort vergessen.', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'die Datei', 'english' => 'file', 'example_sentence' => 'Kannst du mir die Datei per E-Mail schicken?', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'speichern', 'english' => 'to save / store', 'example_sentence' => 'Vergiss nicht, das Dokument zu speichern.', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'die Werbung', 'english' => 'advertising', 'example_sentence' => 'Im Fernsehen kommt zu viel Werbung.', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'die Zeitschrift', 'english' => 'magazine', 'example_sentence' => 'Sie liest gern Zeitschriften über Mode.', 'category' => 'Media & Technology', 'level' => 'B1'],
            ['german' => 'veröffentlichen', 'english' => 'to publish', 'example_sentence' => 'Der Autor hat ein neues Buch veröffentlicht.', 'category' => 'Media & Technology', 'level' => 'B2'],

            // Relationships & Social
            ['german' => 'die Beziehung', 'english' => 'relationship', 'example_sentence' => 'Sie führen eine glückliche Beziehung.', 'category' => 'Relationships & Social', 'level' => 'B1'],
            ['german' => 'sich verloben', 'english' => 'to get engaged', 'example_sentence' => 'Die beiden haben sich letztes Jahr verlobt.', 'category' => 'Relationships & Social', 'level' => 'B2'],
            ['german' => 'sich scheiden lassen', 'english' => 'to get divorced', 'example_sentence' => 'Sie haben sich nach zehn Jahren scheiden lassen.', 'category' => 'Relationships & Social', 'level' => 'B2'],
            ['german' => 'der Nachbar', 'english' => 'neighbor', 'example_sentence' => 'Unser Nachbar ist sehr freundlich.', 'category' => 'Relationships & Social', 'level' => 'B1'],
            ['german' => 'die Verabredung', 'english' => 'appointment / date', 'example_sentence' => 'Ich habe heute Abend eine Verabredung.', 'category' => 'Relationships & Social', 'level' => 'B1'],
            ['german' => 'sich streiten', 'english' => 'to argue / quarrel', 'example_sentence' => 'Die Kinder streiten sich um das Spielzeug.', 'category' => 'Relationships & Social', 'level' => 'B1'],
            ['german' => 'sich versöhnen', 'english' => 'to reconcile', 'example_sentence' => 'Nach dem Streit haben sie sich wieder versöhnt.', 'category' => 'Relationships & Social', 'level' => 'B2'],
            ['german' => 'vertrauen', 'english' => 'to trust', 'example_sentence' => 'Ich vertraue dir vollkommen.', 'category' => 'Relationships & Social', 'level' => 'B1'],
            ['german' => 'die Einladung', 'english' => 'invitation', 'example_sentence' => 'Vielen Dank für die Einladung zur Party.', 'category' => 'Relationships & Social', 'level' => 'B1'],
            ['german' => 'die Gesellschaft', 'english' => 'society / company', 'example_sentence' => 'In unserer Gesellschaft gibt es viele Veränderungen.', 'category' => 'Relationships & Social', 'level' => 'B2'],

            // Law & Government
            ['german' => 'das Gesetz', 'english' => 'law', 'example_sentence' => 'Das neue Gesetz tritt im Januar in Kraft.', 'category' => 'Law & Government', 'level' => 'B2'],
            ['german' => 'der Bürger', 'english' => 'citizen', 'example_sentence' => 'Jeder Bürger hat das Recht zu wählen.', 'category' => 'Law & Government', 'level' => 'B1'],
            ['german' => 'die Wahl', 'english' => 'election / choice', 'example_sentence' => 'Die nächste Wahl findet im Herbst statt.', 'category' => 'Law & Government', 'level' => 'B1'],
            ['german' => 'die Steuer', 'english' => 'tax', 'example_sentence' => 'Die Steuern sind in diesem Land ziemlich hoch.', 'category' => 'Law & Government', 'level' => 'B2'],
            ['german' => 'das Amt', 'english' => 'office / authority', 'example_sentence' => 'Ich muss morgen zum Amt gehen.', 'category' => 'Law & Government', 'level' => 'B1'],
            ['german' => 'der Ausweis', 'english' => 'ID card', 'example_sentence' => 'Zeigen Sie bitte Ihren Ausweis.', 'category' => 'Law & Government', 'level' => 'B1'],
            ['german' => 'die Genehmigung', 'english' => 'permit / approval', 'example_sentence' => 'Für den Umbau brauchen wir eine Genehmigung.', 'category' => 'Law & Government', 'level' => 'B2'],
            ['german' => 'beantragen', 'english' => 'to apply for', 'example_sentence' => 'Ich möchte einen neuen Reisepass beantragen.', 'category' => 'Law & Government', 'level' => 'B2'],
            ['german' => 'die Pflicht', 'english' => 'duty / obligation', 'example_sentence' => 'Es ist deine Pflicht, dich an die Regeln zu halten.', 'category' => 'Law & Government', 'level' => 'B2'],
            ['german' => 'das Recht', 'english' => 'right / law', 'example_sentence' => 'Jeder Mensch hat das Recht auf Bildung.', 'category' => 'Law & Government', 'level' => 'B1'],

            // Communication & Language
            ['german' => 'die Bedeutung', 'english' => 'meaning', 'example_sentence' => 'Was ist die Bedeutung dieses Wortes?', 'category' => 'Communication', 'level' => 'B1'],
            ['german' => 'der Ausdruck', 'english' => 'expression', 'example_sentence' => 'Dieser Ausdruck ist in Österreich sehr üblich.', 'category' => 'Communication', 'level' => 'B1'],
            ['german' => 'übersetzen', 'english' => 'to translate', 'example_sentence' => 'Kannst du diesen Satz ins Englische übersetzen?', 'category' => 'Communication', 'level' => 'B1'],
            ['german' => 'die Aussprache', 'english' => 'pronunciation', 'example_sentence' => 'Die Aussprache dieses Wortes ist schwierig.', 'category' => 'Communication', 'level' => 'B1'],
            ['german' => 'die Muttersprache', 'english' => 'mother tongue', 'example_sentence' => 'Meine Muttersprache ist Deutsch.', 'category' => 'Communication', 'level' => 'B1'],
            ['german' => 'sich ausdrücken', 'english' => 'to express oneself', 'example_sentence' => 'Er kann sich auf Deutsch gut ausdrücken.', 'category' => 'Communication', 'level' => 'B2'],
            ['german' => 'die Verständigung', 'english' => 'communication / understanding', 'example_sentence' => 'Die Verständigung war trotz der Sprachbarriere möglich.', 'category' => 'Communication', 'level' => 'B2'],
            ['german' => 'beherrschen', 'english' => 'to master / command', 'example_sentence' => 'Sie beherrscht drei Fremdsprachen fließend.', 'category' => 'Communication', 'level' => 'B2'],
            ['german' => 'die Redewendung', 'english' => 'idiom / saying', 'example_sentence' => 'Diese Redewendung benutzt man im Alltag oft.', 'category' => 'Communication', 'level' => 'B2'],
            ['german' => 'zusammenfassen', 'english' => 'to summarize', 'example_sentence' => 'Kannst du den Text kurz zusammenfassen?', 'category' => 'Communication', 'level' => 'B2'],

            // Daily Routines & Household
            ['german' => 'aufräumen', 'english' => 'to tidy up', 'example_sentence' => 'Ich muss mein Zimmer aufräumen.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'die Wäsche', 'english' => 'laundry', 'example_sentence' => 'Die Wäsche hängt draußen zum Trocknen.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'bügeln', 'english' => 'to iron', 'example_sentence' => 'Ich muss noch die Hemden bügeln.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'staubsaugen', 'english' => 'to vacuum', 'example_sentence' => 'Samstags staubsauge ich die ganze Wohnung.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'der Haushalt', 'english' => 'household', 'example_sentence' => 'Wir teilen uns die Arbeit im Haushalt.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'abspülen', 'english' => 'to wash dishes', 'example_sentence' => 'Nach dem Essen muss jemand abspülen.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'einkaufen', 'english' => 'to go shopping', 'example_sentence' => 'Ich gehe nach der Arbeit einkaufen.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'die Gewohnheit', 'english' => 'habit', 'example_sentence' => 'Frühes Aufstehen ist eine gute Gewohnheit.', 'category' => 'Daily Life', 'level' => 'B2'],
            ['german' => 'der Alltag', 'english' => 'everyday life', 'example_sentence' => 'Im Alltag trinke ich morgens immer Kaffee.', 'category' => 'Daily Life', 'level' => 'B1'],
            ['german' => 'erledigen', 'english' => 'to take care of / complete', 'example_sentence' => 'Ich muss heute noch ein paar Sachen erledigen.', 'category' => 'Daily Life', 'level' => 'B2'],

            // Abstract Concepts & Verbs
            ['german' => 'sich entscheiden', 'english' => 'to decide', 'example_sentence' => 'Ich kann mich einfach nicht entscheiden.', 'category' => 'Abstract Concepts', 'level' => 'B1'],
            ['german' => 'berücksichtigen', 'english' => 'to consider / take into account', 'example_sentence' => 'Bitte berücksichtigen Sie alle Faktoren.', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'voraussetzen', 'english' => 'to presuppose / require', 'example_sentence' => 'Der Job setzt gute Sprachkenntnisse voraus.', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'beeinflussen', 'english' => 'to influence', 'example_sentence' => 'Das Wetter beeinflusst meine Stimmung.', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'verwirklichen', 'english' => 'to realize / accomplish', 'example_sentence' => 'Sie hat ihren Traum verwirklicht.', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'sich bemühen', 'english' => 'to make an effort', 'example_sentence' => 'Er bemüht sich, pünktlich zu sein.', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'die Erfahrung', 'english' => 'experience', 'example_sentence' => 'Hast du Erfahrung mit Programmierung?', 'category' => 'Abstract Concepts', 'level' => 'B1'],
            ['german' => 'die Möglichkeit', 'english' => 'possibility / opportunity', 'example_sentence' => 'Es gibt die Möglichkeit, von zu Hause zu arbeiten.', 'category' => 'Abstract Concepts', 'level' => 'B1'],
            ['german' => 'die Voraussetzung', 'english' => 'requirement / prerequisite', 'example_sentence' => 'Ein Studium ist die Voraussetzung für diesen Beruf.', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'der Zusammenhang', 'english' => 'context / connection', 'example_sentence' => 'In welchem Zusammenhang steht das?', 'category' => 'Abstract Concepts', 'level' => 'B2'],
            ['german' => 'die Entwicklung', 'english' => 'development', 'example_sentence' => 'Die technische Entwicklung geht schnell voran.', 'category' => 'Abstract Concepts', 'level' => 'B1'],
            ['german' => 'die Verantwortung', 'english' => 'responsibility', 'example_sentence' => 'Eltern tragen eine große Verantwortung.', 'category' => 'Abstract Concepts', 'level' => 'B2'],

            // Leisure & Hobbies
            ['german' => 'der Verein', 'english' => 'club / association', 'example_sentence' => 'Er spielt Fußball in einem Verein.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'die Mannschaft', 'english' => 'team', 'example_sentence' => 'Unsere Mannschaft hat das Spiel gewonnen.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'die Veranstaltung', 'english' => 'event', 'example_sentence' => 'Die Veranstaltung findet im Stadtpark statt.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'die Ausstellung', 'english' => 'exhibition', 'example_sentence' => 'Die Ausstellung im Museum war beeindruckend.', 'category' => 'Leisure & Hobbies', 'level' => 'B2'],
            ['german' => 'die Aufführung', 'english' => 'performance', 'example_sentence' => 'Die Aufführung im Theater war ausverkauft.', 'category' => 'Leisure & Hobbies', 'level' => 'B2'],
            ['german' => 'sich entspannen', 'english' => 'to relax', 'example_sentence' => 'Am Wochenende möchte ich mich einfach entspannen.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'wandern', 'english' => 'to hike', 'example_sentence' => 'Wir wandern gern in den Bergen.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'die Meisterschaft', 'english' => 'championship', 'example_sentence' => 'Das Team hat die Meisterschaft gewonnen.', 'category' => 'Leisure & Hobbies', 'level' => 'B2'],
            ['german' => 'das Ergebnis', 'english' => 'result / score', 'example_sentence' => 'Weißt du schon das Ergebnis vom Spiel?', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'teilnehmen', 'english' => 'to participate', 'example_sentence' => 'Möchtest du am Wettbewerb teilnehmen?', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'sammeln', 'english' => 'to collect', 'example_sentence' => 'Mein Sohn sammelt gern Briefmarken.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],
            ['german' => 'der Zuschauer', 'english' => 'spectator', 'example_sentence' => 'Das Stadion war voller Zuschauer.', 'category' => 'Leisure & Hobbies', 'level' => 'B2'],
            ['german' => 'die Freizeit', 'english' => 'free time / leisure', 'example_sentence' => 'In meiner Freizeit lese ich gern.', 'category' => 'Leisure & Hobbies', 'level' => 'B1'],

            // Feelings & Mental States
            ['german' => 'die Langeweile', 'english' => 'boredom', 'example_sentence' => 'Vor Langeweile habe ich angefangen zu zeichnen.', 'category' => 'Feelings & Mental States', 'level' => 'B1'],
            ['german' => 'die Sehnsucht', 'english' => 'longing / yearning', 'example_sentence' => 'Er hat große Sehnsucht nach seiner Heimat.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],
            ['german' => 'das Heimweh', 'english' => 'homesickness', 'example_sentence' => 'Im Ausland hatte ich oft Heimweh.', 'category' => 'Feelings & Mental States', 'level' => 'B1'],
            ['german' => 'die Eifersucht', 'english' => 'jealousy', 'example_sentence' => 'Eifersucht kann eine Beziehung zerstören.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],
            ['german' => 'das Mitleid', 'english' => 'pity / compassion', 'example_sentence' => 'Ich habe Mitleid mit dem kleinen Hund.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],
            ['german' => 'die Zufriedenheit', 'english' => 'contentment / satisfaction', 'example_sentence' => 'Zufriedenheit ist wichtiger als Reichtum.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],
            ['german' => 'erschöpft', 'english' => 'exhausted', 'example_sentence' => 'Nach dem Lauf war ich völlig erschöpft.', 'category' => 'Feelings & Mental States', 'level' => 'B1'],
            ['german' => 'überrascht', 'english' => 'surprised', 'example_sentence' => 'Ich war überrascht, ihn dort zu sehen.', 'category' => 'Feelings & Mental States', 'level' => 'B1'],
            ['german' => 'erleichtert', 'english' => 'relieved', 'example_sentence' => 'Ich bin erleichtert, dass alles gut gegangen ist.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],
            ['german' => 'besorgt', 'english' => 'worried / concerned', 'example_sentence' => 'Die Eltern sind besorgt um ihr Kind.', 'category' => 'Feelings & Mental States', 'level' => 'B1'],
            ['german' => 'überwältigt', 'english' => 'overwhelmed', 'example_sentence' => 'Sie war von der Überraschung völlig überwältigt.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],
            ['german' => 'zuversichtlich', 'english' => 'optimistic / confident', 'example_sentence' => 'Ich bin zuversichtlich, dass wir es schaffen.', 'category' => 'Feelings & Mental States', 'level' => 'B2'],

            // Directions & Places
            ['german' => 'die Kreuzung', 'english' => 'intersection', 'example_sentence' => 'An der Kreuzung musst du rechts abbiegen.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'geradeaus', 'english' => 'straight ahead', 'example_sentence' => 'Gehen Sie geradeaus bis zur Ampel.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'die Umgebung', 'english' => 'surroundings / area', 'example_sentence' => 'In der Umgebung gibt es viele Restaurants.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'der Stadtteil', 'english' => 'district / neighborhood', 'example_sentence' => 'Dieser Stadtteil ist bei jungen Leuten beliebt.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'die Innenstadt', 'english' => 'city center / downtown', 'example_sentence' => 'Am Samstag fahren wir in die Innenstadt.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'der Vorort', 'english' => 'suburb', 'example_sentence' => 'Sie wohnen in einem ruhigen Vorort.', 'category' => 'Directions & Places', 'level' => 'B2'],
            ['german' => 'die Gegend', 'english' => 'area / region', 'example_sentence' => 'Die Gegend ist bekannt für ihren Wein.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'die Einbahnstraße', 'english' => 'one-way street', 'example_sentence' => 'Vorsicht, das ist eine Einbahnstraße!', 'category' => 'Directions & Places', 'level' => 'B2'],
            ['german' => 'der Bürgersteig', 'english' => 'sidewalk', 'example_sentence' => 'Bitte fahren Sie nicht auf dem Bürgersteig.', 'category' => 'Directions & Places', 'level' => 'B1'],
            ['german' => 'die Ampel', 'english' => 'traffic light', 'example_sentence' => 'Die Ampel ist rot, wir müssen warten.', 'category' => 'Directions & Places', 'level' => 'B1'],

            // Clothing & Appearance
            ['german' => 'anziehen', 'english' => 'to put on / to dress', 'example_sentence' => 'Zieh dir eine warme Jacke an!', 'category' => 'Clothing & Appearance', 'level' => 'B1'],
            ['german' => 'ausziehen', 'english' => 'to take off / to undress', 'example_sentence' => 'Bitte ziehen Sie die Schuhe aus.', 'category' => 'Clothing & Appearance', 'level' => 'B1'],
            ['german' => 'die Größe', 'english' => 'size', 'example_sentence' => 'Haben Sie dieses Hemd in Größe M?', 'category' => 'Clothing & Appearance', 'level' => 'B1'],
            ['german' => 'passen', 'english' => 'to fit', 'example_sentence' => 'Die Hose passt mir nicht mehr.', 'category' => 'Clothing & Appearance', 'level' => 'B1'],
            ['german' => 'die Umkleidekabine', 'english' => 'fitting room', 'example_sentence' => 'Die Umkleidekabinen sind hinten links.', 'category' => 'Clothing & Appearance', 'level' => 'B2'],
            ['german' => 'der Ärmel', 'english' => 'sleeve', 'example_sentence' => 'Die Ärmel sind mir etwas zu lang.', 'category' => 'Clothing & Appearance', 'level' => 'B2'],
            ['german' => 'der Stoff', 'english' => 'fabric / material', 'example_sentence' => 'Dieser Stoff fühlt sich sehr weich an.', 'category' => 'Clothing & Appearance', 'level' => 'B2'],
            ['german' => 'gestreift', 'english' => 'striped', 'example_sentence' => 'Er trägt gern gestreifte Hemden.', 'category' => 'Clothing & Appearance', 'level' => 'B2'],
            ['german' => 'kariert', 'english' => 'checkered / plaid', 'example_sentence' => 'Das karierte Kleid steht dir gut.', 'category' => 'Clothing & Appearance', 'level' => 'B2'],
            ['german' => 'der Schmuck', 'english' => 'jewelry', 'example_sentence' => 'Sie trägt gern goldenen Schmuck.', 'category' => 'Clothing & Appearance', 'level' => 'B1'],

            // Time & Scheduling
            ['german' => 'der Termin', 'english' => 'appointment', 'example_sentence' => 'Ich habe morgen einen Termin beim Zahnarzt.', 'category' => 'Time & Scheduling', 'level' => 'B1'],
            ['german' => 'verschieben', 'english' => 'to postpone / to move', 'example_sentence' => 'Können wir das Treffen auf Freitag verschieben?', 'category' => 'Time & Scheduling', 'level' => 'B2'],
            ['german' => 'rechtzeitig', 'english' => 'on time / in time', 'example_sentence' => 'Wir sind rechtzeitig am Flughafen angekommen.', 'category' => 'Time & Scheduling', 'level' => 'B1'],
            ['german' => 'die Dauer', 'english' => 'duration', 'example_sentence' => 'Die Dauer des Films beträgt zwei Stunden.', 'category' => 'Time & Scheduling', 'level' => 'B2'],
            ['german' => 'voraussichtlich', 'english' => 'expected / estimated', 'example_sentence' => 'Der Zug kommt voraussichtlich um 15 Uhr an.', 'category' => 'Time & Scheduling', 'level' => 'B2'],
            ['german' => 'gleichzeitig', 'english' => 'simultaneous / at the same time', 'example_sentence' => 'Er kann nicht zwei Dinge gleichzeitig machen.', 'category' => 'Time & Scheduling', 'level' => 'B2'],
            ['german' => 'allmählich', 'english' => 'gradually', 'example_sentence' => 'Es wird allmählich wärmer draußen.', 'category' => 'Time & Scheduling', 'level' => 'B2'],
            ['german' => 'inzwischen', 'english' => 'meanwhile', 'example_sentence' => 'Ich koche, und du deckst inzwischen den Tisch.', 'category' => 'Time & Scheduling', 'level' => 'B1'],
            ['german' => 'ständig', 'english' => 'constantly', 'example_sentence' => 'Er schaut ständig auf sein Handy.', 'category' => 'Time & Scheduling', 'level' => 'B1'],
            ['german' => 'gelegentlich', 'english' => 'occasionally', 'example_sentence' => 'Gelegentlich gehe ich ins Kino.', 'category' => 'Time & Scheduling', 'level' => 'B2'],
        ];

        foreach ($cards as $card) {
            FlashCard::updateOrCreate(
                ['german' => $card['german'], 'category' => $card['category']],
                $card,
            );
        }
    }
}
